set(GUI_PUBLIC_INCLUDES
    ${GUI_PUBLIC_INCLUDES}
    QAction
    QActionEvent
    QActionGroup
    QApplication
    QGuiApplication
    QBoxLayout
    QClipboard
    QClipboardEvent
    QCloseEvent
    QColorGroup
    QContextMenuEvent
    QCursor
    QCursorShape
    QDesktopWidget
    QDrag
    QDragEnterEvent
    QDragLeaveEvent
    QDragMoveEvent
    QDragResponseEvent
    QDropEvent
    QEvent
    QFileOpenEvent
    QFocusEvent
    QFormLayout
    QGenericPlugin
    QGenericPluginFactory
    QGesture
    QGestureEvent
    QGestureRecognizer
    QGridLayout
    QHBoxLayout
    QHelpEvent
    QHideEvent
    QHoverEvent
    QIconDragEvent
    QInputEvent
    QInputMethod
    QInputMethodEvent
    QKeyEvent
    QKeySequence
    QLayout
    QLayoutItem
    QLayoutIterator
    QMacMime
    QMacPasteboardMime
    QMenubarUpdatedEvent
    QMimeSource
    QMouseEvent
    QMoveEvent
    QOffscreenSurface
    QOpenGLContext
    QOpenGLWindow
    QPaintDeviceWindow
    QPaintEvent
    QPalette
    QPanGesture
    QPinchGesture
    QPixelFormat
    QRasterWindow
    QResizeEvent
    QScreen
    QSessionManager
    QShortcut
    QShortcutEvent
    QShowEvent
    QSizePolicy
    QSound
    QSpacerItem
    QStackedLayout
    QStatusTipEvent
    QStyleHints
    QSurface
    QSurfaceFormat
    QSwipeGesture
    QTabletEvent
    QTapAndHoldGesture
    QTapGesture
    QToolBarChangeEvent
    QToolTip
    QTouchDevice
    QTouchEvent
    QUpdateLaterEvent
    QVBoxLayout
    QWhatsThis
    QWhatsThisClickedEvent
    QWheelEvent
    QWidget
    QWidgetAction
    QWidgetData
    QWidgetItem
    QWidgetItemV2
    QWidgetList
    QWidgetMapper
    QWidgetSet
    QWindow
    QWindowStateChangeEvent
    QWindowSystemInterface
    QWindowsMime
    QtGui
)

set(GUI_INCLUDES
    ${GUI_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qaction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qactionevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qactiongroup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguiapplication.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qboxlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboardevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcloseevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcolorgroup.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcontextmenuevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursorshape.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdrag.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdragenterevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdragleaveevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdragmoveevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdragresponseevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdropevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qfileopenevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qfocusevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qformlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgenericplugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgenericpluginfactory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgestureevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturerecognizer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgridlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhboxlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhelpevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhideevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhoverevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qicondragevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputmethod.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputmethodevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeyevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeysequence.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmacdefines_mac.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmacmime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmacpasteboardmime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmenubarupdatedevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmimesource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmouseevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmoveevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qoffscreensurface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qopenglcontext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qopenglwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpaintdevicewindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpaintevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpalette.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpangesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpinchgesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpixelformat.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qrasterwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qresizeevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qscreen.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsessionmanager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcut.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcutevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshowevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsizepolicy.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsound.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qspaceritem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstackedlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstatustipevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstylehints.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsurface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsurfaceformat.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qswipegesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtabletevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtapandholdgesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtapgesture.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtevents.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtoolbarchangeevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtooltip.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtouchdevice.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtouchevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qupdatelaterevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qvboxlayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwhatsthis.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwhatsthisclickedevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwheelevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetaction.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetdata.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetitemv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetlist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetmapper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetset.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowdefs.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowdefs_win.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowsmime.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowstatechangeevent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowsysteminterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/cs_carbon_wrapper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtgui.h
)

set(GUI_PRIVATE_INCLUDES
    ${GUI_PRIVATE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qaction_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguiapplication_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaapplication_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaapplicationdelegate_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaintrospection_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoamenuloader_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoapanel_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoasharedwindowmethods_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaview_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoawindow_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoawindowdelegate_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoawindowcustomthemeframe_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qevent_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_glib_qpa_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_x11_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesture_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturemanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguieventdispatcher_glib_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguiplatformplugin_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhexstring_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhighdpiscaling_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputdevicemanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputmethod_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkde_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeysequence_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayout_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutengine_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qnsthemeframe_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qnstitledframe_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qnsframeview_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmacgesturerecognizer_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmultitouch_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qopenglcontext_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpaintdevicewindow_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qscreen_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshapedpixmapdndwindow_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsessionmanager_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcutmap_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsimpledrag_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsound_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstandardgestures_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtouchdevice_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qt_cocoa_helpers_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qt_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetaction_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindow_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowcontainer_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowsysteminterface_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/cs_carbon_wrapper_p.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qaction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qactiongroup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qboxlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdrag.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qevent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qformlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesture.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturerecognizer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgesturemanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qgridlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguivariant.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qhighdpiscaling.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputdevicemanager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qinputmethod.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeysequence.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutengine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qlayoutitem.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmime.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qoffscreensurface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qopenglcontext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qopenglwindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpaintdevicewindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpalette.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qrasterwindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsimpledrag.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qscreen.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshapedpixmapdndwindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcut.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qshortcutmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstackedlayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstandardgestures.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qstylehints.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsurface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsurfaceformat.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtooltip.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qtouchdevice.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwhatsthis.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetaction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowcontainer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwindowsysteminterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguiplatformplugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsound.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qpixelformat.cpp
)

if(X11_FOUND)
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmotifdnd_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsound_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidgetcreate_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkde.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_x11.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qguieventdispatcher_glib.cpp
    )
endif()

if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard_win.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor_win.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget_win.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd_win.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmime_win.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsound_win.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qole_win.cpp
    )
    add_definitions(-DQT_NO_DIRECTDRAW)

elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qclipboard_mac.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmime_mac.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qt_mac.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qkeymapper_mac.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcursor_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdnd_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qsound_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qapplication_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qwidget_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoapanel_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaview_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoawindow_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoawindowdelegate_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoamenuloader_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaapplication_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaapplicationdelegate_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qt_cocoa_helpers_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qdesktopwidget_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qeventdispatcher_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoawindowcustomthemeframe_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmacgesturerecognizer_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qmultitouch_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/qcocoaintrospection_mac.mm
        ${CMAKE_CURRENT_SOURCE_DIR}/kernel/cs_carbon_wrapper.mm
    )
    set(EXTRA_GUI_LDFLAGS
        ${EXTRA_GUI_LDFLAGS}
        -framework AppKit
    )
endif()
