/***********************************************************************
*
* Copyright (c) 2012-2018 Barbara Geller
* Copyright (c) 2012-2018 Ansel Sermersheim
* Copyright (c) 2012-2016 Digia Plc and/or its subsidiary(-ies).
* Copyright (c) 2008-2012 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
*
* This file is part of CopperSpice.
*
* CopperSpice is free software. You can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public License
* version 2.1 as published by the Free Software Foundation.
*
* CopperSpice is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* <http://www.gnu.org/licenses/>.
*
***********************************************************************/

// originally generated using util/xkbdatagen

struct xkbLayoutData_struct {
   const char *layout;
   const char *variant;                // 0 means any variant
   Qt::LayoutDirection direction;
   QLocale::Language language;
   QLocale::Country country;
};

static xkbLayoutData_struct xkbLayoutData[] = {
   { "us", "",                  Qt::LeftToRight, QLocale::English, QLocale::UnitedStates },
   { "us", "intl",              Qt::LeftToRight, QLocale::English, QLocale::UnitedStates },
   { "us", "alt-intl",          Qt::LeftToRight, QLocale::English, QLocale::UnitedStates },
   { "us", "dvorak",            Qt::LeftToRight, QLocale::English, QLocale::UnitedStates },
   { "us", "rus",               Qt::LeftToRight, QLocale::Russian, QLocale::UnitedStates },

   { "ara", "",                 Qt::RightToLeft, QLocale::Arabic, QLocale::UnitedArabEmirates },
   { "ara", "azerty",           Qt::RightToLeft, QLocale::Arabic, QLocale::UnitedArabEmirates },
   { "ara", "azerty_digits",    Qt::RightToLeft, QLocale::Arabic, QLocale::UnitedArabEmirates },
   { "ara", "digits",           Qt::RightToLeft, QLocale::Arabic, QLocale::UnitedArabEmirates },
   { "ara", "qwerty",           Qt::RightToLeft, QLocale::Arabic, QLocale::UnitedArabEmirates },
   { "ara", "qwerty_digits",    Qt::RightToLeft, QLocale::Arabic, QLocale::UnitedArabEmirates },

   { "al", "", Qt::LeftToRight, QLocale::Albanian, QLocale::Albania },
   { "am", "", Qt::LeftToRight, QLocale::Armenian, QLocale::Armenia },

   { "am", "phonetic",          Qt::LeftToRight, QLocale::Armenian, QLocale::Armenia },
   { "az", "",                  Qt::LeftToRight, QLocale::Azerbaijani, QLocale::Azerbaijan },
   { "az", "cyrillic",          Qt::LeftToRight, QLocale::Azerbaijani, QLocale::Azerbaijan },
   { "by", "",                  Qt::LeftToRight, QLocale::Byelorussian, QLocale::Belarus },
   { "by", "winkeys",           Qt::LeftToRight, QLocale::Byelorussian, QLocale::Belarus },
   { "be", "",                  Qt::LeftToRight, QLocale::Dutch, QLocale::Belgium },
   { "be", "iso-alternate",     Qt::LeftToRight, QLocale::Dutch, QLocale::Belgium },
   { "be", "nodeadkeys",        Qt::LeftToRight, QLocale::Dutch, QLocale::Belgium },
   { "be", "sundeadkeys",       Qt::LeftToRight, QLocale::Dutch, QLocale::Belgium },
   { "bd", "",                  Qt::LeftToRight, QLocale::Bengali, QLocale::Bangladesh },
   { "bd", "probhat",           Qt::LeftToRight, QLocale::Bengali, QLocale::Bangladesh },
   { "in", "",                  Qt::LeftToRight, QLocale::Hindi, QLocale::India },
   { "in", "ben",               Qt::LeftToRight, QLocale::Bengali, QLocale::India },
   { "in", "ben_probhat",       Qt::LeftToRight, QLocale::Bengali, QLocale::India },
   { "in", "guj",               Qt::LeftToRight, QLocale::Gujarati, QLocale::India },
   { "in", "guru",              Qt::LeftToRight, QLocale::Punjabi, QLocale::India },
   { "in", "kan",               Qt::LeftToRight, QLocale::Kannada, QLocale::India },
   { "in", "mal",               Qt::LeftToRight, QLocale::Malayalam, QLocale::India },
   { "in", "ori",               Qt::LeftToRight, QLocale::Oriya, QLocale::India },
   { "in", "tam_unicode",       Qt::LeftToRight, QLocale::Tamil, QLocale::India },
   { "in", "tam_TAB",           Qt::LeftToRight, QLocale::Tamil, QLocale::India },
   { "in", "tam_TSCII",         Qt::LeftToRight, QLocale::Tamil, QLocale::India },
   { "in", "tam",               Qt::LeftToRight, QLocale::Tamil, QLocale::India },
   { "in", "tel",               Qt::LeftToRight, QLocale::Telugu, QLocale::India },
   { "in", "urd",               Qt::RightToLeft, QLocale::Urdu, QLocale::India },
   { "ba", "",                  Qt::LeftToRight, QLocale::Bosnian, QLocale::BosniaAndHerzegowina },
   { "br", "",                  Qt::LeftToRight, QLocale::Portuguese, QLocale::Brazil },
   { "br", "nodeadkeys",        Qt::LeftToRight, QLocale::Portuguese, QLocale::Brazil },
   { "bg", "",                  Qt::LeftToRight, QLocale::Bulgarian, QLocale::Bulgaria },
   { "bg", "phonetic",          Qt::LeftToRight, QLocale::Bulgarian, QLocale::Bulgaria },
   { "mm", "",                  Qt::LeftToRight, QLocale::Burmese, QLocale::Myanmar },

   { "ca", "",                  Qt::LeftToRight, QLocale::English, QLocale::Canada },
   { "ca", "fr-dvorak",         Qt::LeftToRight, QLocale::French, QLocale::Canada },
   { "ca", "fr-legacy",         Qt::LeftToRight, QLocale::French, QLocale::Canada },
   { "ca", "multi",             Qt::LeftToRight, QLocale::English, QLocale::Canada },
   { "ca", "multi-2gr",         Qt::LeftToRight, QLocale::English, QLocale::Canada },
   { "ca", "ike",               Qt::LeftToRight, QLocale::Inuktitut, QLocale::Canada },
   { "hr", "",                  Qt::LeftToRight, QLocale::Croatian, QLocale::Croatia },
   { "hr", "us",                Qt::LeftToRight, QLocale::Croatian, QLocale::Croatia },
   { "cz", "",                  Qt::LeftToRight, QLocale::Czech, QLocale::CzechRepublic },
   { "cz", "bksl",              Qt::LeftToRight, QLocale::Czech, QLocale::CzechRepublic },

   { "cz", "qwerty",            Qt::LeftToRight, QLocale::Czech, QLocale::CzechRepublic },
   { "cz", "qwerty_bksl",       Qt::LeftToRight, QLocale::Czech, QLocale::CzechRepublic },
   { "dk", "",                  Qt::LeftToRight, QLocale::Danish, QLocale::Denmark },
   { "dk", "nodeadkeys",        Qt::LeftToRight, QLocale::Danish, QLocale::Denmark },
   { "nl", "",                  Qt::LeftToRight, QLocale::Dutch, QLocale::Netherlands },
   { "bt", "",                  Qt::LeftToRight, QLocale::Bhutani, QLocale::Bhutan },
   { "ee", "",                  Qt::LeftToRight, QLocale::Estonian, QLocale::Estonia },
   { "ee", "nodeadkeys",        Qt::LeftToRight, QLocale::Estonian, QLocale::Estonia },
   { "ir", "",                  Qt::RightToLeft, QLocale::Persian, QLocale::Iran },
   { "fo", "",                  Qt::LeftToRight, QLocale::Faroese, QLocale::FaroeIslands },
   { "fo", "nodeadkeys",        Qt::LeftToRight, QLocale::Faroese, QLocale::FaroeIslands },
   { "fi", "",                  Qt::LeftToRight, QLocale::Finnish, QLocale::Finland },
   { "fi", "nodeadkeys",        Qt::LeftToRight, QLocale::Finnish, QLocale::Finland },
   { "fi", "smi",               Qt::LeftToRight, QLocale::Finnish, QLocale::Finland },
   { "fr", "",                  Qt::LeftToRight, QLocale::French, QLocale::France },
   { "fr", "nodeadkeys",        Qt::LeftToRight, QLocale::French, QLocale::France },
   { "fr", "sundeadkeys",       Qt::LeftToRight, QLocale::French, QLocale::France },
   { "fr", "latin9",            Qt::LeftToRight, QLocale::French, QLocale::France },
   { "fr", "latin9_nodeadkeys", Qt::LeftToRight, QLocale::French, QLocale::France },
   { "fr", "latin9_sundeadkeys",Qt::LeftToRight, QLocale::French, QLocale::France },
   { "fr", "dvorak",            Qt::LeftToRight, QLocale::French, QLocale::France },
   { "ge", "",                  Qt::LeftToRight, QLocale::Georgian, QLocale::Georgia },
   { "ge", "ru",                Qt::LeftToRight, QLocale::Russian, QLocale::Georgia },
   { "de", "",                  Qt::LeftToRight, QLocale::German, QLocale::Germany },
   { "de", "deadacute",         Qt::LeftToRight, QLocale::German, QLocale::Germany },
   { "de", "deadgraveacute",    Qt::LeftToRight, QLocale::German, QLocale::Germany },
   { "de", "nodeadkeys",        Qt::LeftToRight, QLocale::German, QLocale::Germany },
   { "de", "ro",                Qt::LeftToRight, QLocale::Romanian, QLocale::Germany },
   { "de", "ro_nodeadkeys",     Qt::LeftToRight, QLocale::Romanian, QLocale::Germany },
   { "de", "dvorak",            Qt::LeftToRight, QLocale::German, QLocale::Germany },
   { "gr", "",                  Qt::LeftToRight, QLocale::Greek, QLocale::Greece },
   { "gr", "extended",          Qt::LeftToRight, QLocale::Greek, QLocale::Greece },
   { "gr", "nodeadkeys",        Qt::LeftToRight, QLocale::Greek, QLocale::Greece },
   { "gr", "polytonic",         Qt::LeftToRight, QLocale::Greek, QLocale::Greece },
   { "hu", "",                  Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "standard",          Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "nodeadkeys",        Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "qwerty",            Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },

   { "hu", "101_qwertz_comma_dead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwertz_comma_nodead", Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwertz_dot_dead",     Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwertz_dot_nodead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwerty_comma_dead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwerty_comma_nodead", Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwerty_dot_dead",     Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "101_qwerty_dot_nodead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwertz_comma_dead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwertz_comma_nodead", Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwertz_dot_dead",     Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwertz_dot_nodead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwerty_comma_dead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwerty_comma_nodead", Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwerty_dot_dead",     Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },
   { "hu", "102_qwerty_dot_nodead",   Qt::LeftToRight, QLocale::Hungarian, QLocale::Hungary },

   { "is", "",                  Qt::LeftToRight, QLocale::Icelandic,  QLocale::Iceland },
   { "is", "Sundeadkeys",       Qt::LeftToRight, QLocale::Icelandic,  QLocale::Iceland },
   { "is", "nodeadkeys",        Qt::LeftToRight, QLocale::Icelandic,  QLocale::Iceland },
   { "il", "",                  Qt::RightToLeft, QLocale::Hebrew,     QLocale::Israel },
   { "il", "lyx",               Qt::RightToLeft, QLocale::Hebrew,     QLocale::Israel },
   { "il", "si1452",            Qt::RightToLeft, QLocale::Hebrew,     QLocale::Israel },
   { "il", "phonetic",          Qt::RightToLeft, QLocale::Hebrew,     QLocale::Israel },
   { "it", "",                  Qt::LeftToRight, QLocale::Italian,    QLocale::Italy },
   { "it", "nodeadkeys",        Qt::LeftToRight, QLocale::Italian,    QLocale::Italy },
   { "jp", "",                  Qt::LeftToRight, QLocale::Japanese,   QLocale::Japan },
   { "kg", "",                  Qt::LeftToRight, QLocale::Kirghiz,    QLocale::Kyrgyzstan },
   { "la", "",                  Qt::LeftToRight, QLocale::Lao,        QLocale::Laos  },
   { "latam", "",               Qt::LeftToRight, QLocale::Spanish,    QLocale::Mexico },
   { "latam", "nodeadkeys",     Qt::LeftToRight, QLocale::Spanish,    QLocale::Mexico },
   { "latam", "sundeadkeys",    Qt::LeftToRight, QLocale::Spanish,    QLocale::Mexico },
   { "lt", "",                  Qt::LeftToRight, QLocale::Lithuanian, QLocale::Lithuania },
   { "lt", "std",               Qt::LeftToRight, QLocale::Lithuanian, QLocale::Lithuania },
   { "lt", "us",                Qt::LeftToRight, QLocale::Lithuanian, QLocale::Lithuania },
   { "lv", "",                  Qt::LeftToRight, QLocale::Latvian,    QLocale::Latvia },
   { "lv", "apostrophe",        Qt::LeftToRight, QLocale::Latvian,    QLocale::Latvia },
   { "lv", "tilde", Qt::LeftToRight, QLocale::Latvian, QLocale::Latvia },
   { "lv", "fkey", Qt::LeftToRight, QLocale::Latvian, QLocale::Latvia },
   { "mao", "", Qt::LeftToRight, QLocale::Maori, QLocale::NewZealand },
   { "mkd", "", Qt::LeftToRight, QLocale::Macedonian, QLocale::Macedonia },
   { "mkd", "nodeadkeys", Qt::LeftToRight, QLocale::Macedonian, QLocale::Macedonia },
   { "mt", "", Qt::LeftToRight, QLocale::Maltese, QLocale::Malta },
   { "mt", "us", Qt::LeftToRight, QLocale::Maltese, QLocale::Malta },
   { "mn", "", Qt::LeftToRight, QLocale::Mongolian, QLocale::Mongolia },
   { "no", "", Qt::LeftToRight, QLocale::Norwegian, QLocale::Norway },
   { "no", "nodeadkeys", Qt::LeftToRight, QLocale::Norwegian, QLocale::Norway },
   { "no", "dvorak", Qt::LeftToRight, QLocale::Norwegian, QLocale::Norway },
   { "no", "smi", Qt::LeftToRight, QLocale::Norwegian, QLocale::Norway },
   { "no", "smi_nodeadkeys", Qt::LeftToRight, QLocale::Norwegian, QLocale::Norway },
   { "pl", "", Qt::LeftToRight, QLocale::Polish, QLocale::Poland },
   { "pl", "qwertz", Qt::LeftToRight, QLocale::Polish, QLocale::Poland },
   { "pl", "dvorak", Qt::LeftToRight, QLocale::Polish, QLocale::Poland },
   { "pl", "dvorak_quotes", Qt::LeftToRight, QLocale::Polish, QLocale::Poland },
   { "pl", "dvorak_altquotes", Qt::LeftToRight, QLocale::Polish, QLocale::Poland },
   { "pt", "", Qt::LeftToRight, QLocale::Portuguese, QLocale::Portugal },
   { "pt", "nodeadkeys", Qt::LeftToRight, QLocale::Portuguese, QLocale::Portugal },
   { "pt", "sundeadkeys", Qt::LeftToRight, QLocale::Portuguese, QLocale::Portugal },

   { "ro", "",                  Qt::LeftToRight, QLocale::Romanian, QLocale::Romania },
   { "ro", "us",                Qt::LeftToRight, QLocale::English, QLocale::Romania },
   { "ro", "de",                Qt::LeftToRight, QLocale::German, QLocale::Romania },
   { "ru", "",                  Qt::LeftToRight, QLocale::Russian, QLocale::RussianFederation },
   { "ru", "phonetic",          Qt::LeftToRight, QLocale::Russian, QLocale::RussianFederation },
   { "ru", "typewriter",        Qt::LeftToRight, QLocale::Russian, QLocale::RussianFederation },
   { "ru", "winkeys",           Qt::LeftToRight, QLocale::Russian, QLocale::RussianFederation },
   { "srp", "",                 Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "yz",               Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "latin",            Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "latinunicode",     Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "latinyz",          Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "latinunicodeyz",   Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "alternatequotes",  Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },
   { "srp", "latinalternatequotes", Qt::LeftToRight, QLocale::Serbian, QLocale::Serbia },

   { "si", "", Qt::LeftToRight, QLocale::Slovenian, QLocale::Slovenia },
   { "sk", "", Qt::LeftToRight, QLocale::Slovak, QLocale::Slovakia },
   { "sk", "bksl", Qt::LeftToRight, QLocale::Slovak, QLocale::Slovakia },
   { "sk", "qwerty", Qt::LeftToRight, QLocale::Slovak, QLocale::Slovakia },
   { "sk", "qwerty_bksl", Qt::LeftToRight, QLocale::Slovak, QLocale::Slovakia },
   { "es", "", Qt::LeftToRight, QLocale::Spanish, QLocale::Spain },
   { "es", "nodeadkeys", Qt::LeftToRight, QLocale::Spanish, QLocale::Spain },
   { "es", "sundeadkeys", Qt::LeftToRight, QLocale::Spanish, QLocale::Spain },
   { "es", "dvorak", Qt::LeftToRight, QLocale::Spanish, QLocale::Spain },
   { "se", "", Qt::LeftToRight, QLocale::Swedish, QLocale::Sweden },
   { "se", "nodeadkeys", Qt::LeftToRight, QLocale::Swedish, QLocale::Sweden },
   { "se", "dvorak", Qt::LeftToRight, QLocale::Swedish, QLocale::Sweden },
   { "se", "rus", Qt::LeftToRight, QLocale::Russian, QLocale::Sweden },
   { "se", "rus_nodeadkeys", Qt::LeftToRight, QLocale::Russian, QLocale::Sweden },
   { "se", "smi", Qt::LeftToRight, QLocale::Swedish, QLocale::Sweden },
   { "ch", "", Qt::LeftToRight, QLocale::German, QLocale::Switzerland },
   { "ch", "de_nodeadkeys", Qt::LeftToRight, QLocale::German, QLocale::Switzerland },
   { "ch", "de_sundeadkeys", Qt::LeftToRight, QLocale::German, QLocale::Switzerland },
   { "ch", "fr", Qt::LeftToRight, QLocale::French, QLocale::Switzerland },
   { "ch", "fr_nodeadkeys", Qt::LeftToRight, QLocale::French, QLocale::Switzerland },
   { "ch", "fr_sundeadkeys", Qt::LeftToRight, QLocale::French, QLocale::Switzerland },
   { "sy", "", Qt::RightToLeft, QLocale::Syriac, QLocale::SyrianArabRepublic },
   { "sy", "syc", Qt::RightToLeft, QLocale::Syriac, QLocale::SyrianArabRepublic },
   { "sy", "syc_phonetic", Qt::RightToLeft, QLocale::Syriac, QLocale::SyrianArabRepublic },
   { "tj", "", Qt::LeftToRight, QLocale::Tajik, QLocale::Tajikistan },

   { "lk", "",                  Qt::LeftToRight, QLocale::Sinhala, QLocale::SriLanka },
   { "lk", "tam_unicode",       Qt::LeftToRight, QLocale::Tamil,   QLocale::SriLanka },
   { "lk", "tam_TAB",           Qt::LeftToRight, QLocale::Tamil,   QLocale::SriLanka },
   { "lk", "tam_TSCII",         Qt::LeftToRight, QLocale::Tamil,   QLocale::SriLanka },
   { "lk", "sin_phonetic",      Qt::LeftToRight, QLocale::Sinhala, QLocale::SriLanka },

   { "th", "",                  Qt::LeftToRight, QLocale::Thai, QLocale::Thailand },
   { "th", "tis",               Qt::LeftToRight, QLocale::Thai, QLocale::Thailand },
   { "th", "pat",               Qt::LeftToRight, QLocale::Thai, QLocale::Thailand },
   { "tr", "",                  Qt::LeftToRight, QLocale::Turkish, QLocale::Turkey },
   { "tr", "f",                 Qt::LeftToRight, QLocale::Turkish, QLocale::Turkey },
   { "tr", "alt",               Qt::LeftToRight, QLocale::Turkish, QLocale::Turkey },
   { "ua", "",                  Qt::LeftToRight, QLocale::Ukrainian, QLocale::Ukraine },
   { "ua", "phonetic",          Qt::LeftToRight, QLocale::Ukrainian, QLocale::Ukraine },
   { "ua", "typewriter",        Qt::LeftToRight, QLocale::Ukrainian, QLocale::Ukraine },
   { "ua", "winkeys",           Qt::LeftToRight, QLocale::Ukrainian, QLocale::Ukraine },
   { "ua", "rstu",              Qt::LeftToRight, QLocale::Ukrainian, QLocale::Ukraine },
   { "ua", "rstu_ru",           Qt::LeftToRight, QLocale::Ukrainian, QLocale::Ukraine },
   { "gb", "",                  Qt::LeftToRight, QLocale::English, QLocale::UnitedKingdom },
   { "gb", "intl",              Qt::LeftToRight, QLocale::English, QLocale::UnitedKingdom },
   { "gb", "dvorak",            Qt::LeftToRight, QLocale::English, QLocale::UnitedKingdom },
   { "uz", "",                  Qt::LeftToRight, QLocale::Uzbek, QLocale::Uzbekistan },
   { "vn", "",                  Qt::LeftToRight, QLocale::Vietnamese, QLocale::Vietnam },
   { "nec_vndr/jp", "",         Qt::LeftToRight, QLocale::Japanese, QLocale::Japan },
   { "ie", "",                  Qt::LeftToRight, QLocale::Irish, QLocale::Ireland },
   { "ie", "CloGaelach",        Qt::LeftToRight, QLocale::Gaelic, QLocale::Ireland },
   { "ie", "UnicodeExpert",     Qt::LeftToRight, QLocale::Irish, QLocale::Ireland },
   { "ie", "ogam",              Qt::LeftToRight, QLocale::Gaelic, QLocale::Ireland },
   { "ie", "ogam_is434",        Qt::LeftToRight, QLocale::Gaelic, QLocale::Ireland },
   { "pk", "",                  Qt::RightToLeft, QLocale::Urdu, QLocale::Pakistan },
   { 0, 0,                      Qt::LeftToRight, QLocale::C, QLocale::AnyCountry }
};

