#ifndef QTMULTIMEDIA_H
#define QTMULTIMEDIA_H

#include <qtcore.h>
#include <qtgui.h>

#include <qabstractvideobuffer.h>
#include <qabstractvideofilter.h>
#include <qabstractvideosurface.h>
#include <qaudio.h>
#include <qaudiobuffer.h>
#include <qaudiodecoder.h>
#include <qaudiodecodercontrol.h>
#include <qaudiodeviceinfo.h>
#include <qaudioencodersettingscontrol.h>
#include <qaudioformat.h>
#include <qaudioinput.h>
#include <qaudioinputselectorcontrol.h>
#include <qaudiooutput.h>
#include <qaudiooutputselectorcontrol.h>
#include <qaudioprobe.h>
#include <qaudiorecorder.h>
#include <qaudiorolecontrol.h>
#include <qaudiosystem.h>
#include <qaudiosystemplugin.h>
#include <qcamera.h>
#include <qcameracontrol.h>
#include <qcameraexposure.h>
#include <qcameraexposurecontrol.h>
#include <qcamerafeedbackcontrol.h>
#include <qcameraflashcontrol.h>
#include <qcamerafocus.h>
#include <qcamerafocuscontrol.h>
#include <qcameraimagecapture.h>
#include <qcameraimagecapturecontrol.h>
#include <qcameraimageprocessing.h>
#include <qcameraimageprocessingcontrol.h>
#include <qcamerainfo.h>
#include <qcamerainfocontrol.h>
#include <qcameralockscontrol.h>
#include <qcameraviewfinder.h>
#include <qcameraviewfindersettings.h>
#include <qcamerazoomcontrol.h>
#include <qimageencodercontrol.h>
#include <qmediaaudioprobecontrol.h>
#include <qmediaavailabilitycontrol.h>
#include <qmediabindableinterface.h>
#include <qmediacontainercontrol.h>
#include <qmediacontent.h>
#include <qmediacontrol.h>
#include <qmediaencodersettings.h>
#include <qmediagaplessplaybackcontrol.h>
#include <qmediametadata.h>
#include <qmedianetworkaccesscontrol.h>
#include <qmediaobject.h>
#include <qmediaplayer.h>
#include <qmediaplayercontrol.h>
#include <qmediaplaylist.h>
#include <qmediarecorder.h>
#include <qmediarecordercontrol.h>
#include <qmediaresource.h>
#include <qmediaservice.h>
#include <qmediaservice_provider_plugin.h>
#include <qmediastreamscontrol.h>
#include <qmediatimerange.h>
#include <qmediavideoprobecontrol.h>
#include <qmetadatareadercontrol.h>
#include <qmetadatawritercontrol.h>
#include <qmultimedia.h>
#include <qradiodata.h>
#include <qradiodatacontrol.h>
#include <qradiotuner.h>
#include <qradiotunercontrol.h>
#include <qsound.h>
#include <qsoundeffect.h>
#include <qvideoframe.h>
#include <qvideoprobe.h>
#include <qvideorenderercontrol.h>
#include <qvideosurfaceformat.h>
#include <qvideowidget.h>
#include <qvideowindowcontrol.h>
#endif
