list(APPEND XMLPATTERNS_PRIVATE_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qabstractfunctionfactory_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qaccessorfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qaggregatefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qaggregator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qassemblestringfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qbooleanfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcomparescaseaware_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcomparestringfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcomparingaggregator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qconstructorfunctionsfactory_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcontextfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcurrentfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdatetimefn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdatetimefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdeepequalfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdocumentfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qelementavailablefn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qerrorfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionargument_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionavailablefn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctioncall_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionfactorycollection_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionfactory_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionsignature_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qgenerateidfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qnodefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qnumericfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qpatternmatchingfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qpatternplatform_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qqnamefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qresolveurifn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsequencefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsequencegeneratingfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qstaticbaseuricontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qstaticnamespacescontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qstringvaluefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsubstringfns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsystempropertyfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qtimezonefns_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qtracefn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qtypeavailablefn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedentitypublicidfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedentityurifn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedtextavailablefn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedtextfn_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcontextnodechecker_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qxpath10corefunctions_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qxpath20corefunctions_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qxslt20corefunctions_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcomparingaggregator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdatetimefns.cpp
)

target_sources(CsXmlPatterns
   PRIVATE
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qabstractfunctionfactory.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qaccessorfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qaggregatefns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qaggregator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qassemblestringfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qbooleanfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcomparescaseaware.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcomparestringfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qconstructorfunctionsfactory.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcontextfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcontextnodechecker.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qcurrentfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdatetimefn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdeepequalfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qdocumentfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qelementavailablefn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qerrorfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionargument.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionavailablefn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctioncall.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionfactorycollection.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionfactory.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qfunctionsignature.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qgenerateidfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qnodefns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qnumericfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qpatternmatchingfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qpatternplatform.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qqnamefns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qresolveurifn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsequencefns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsequencegeneratingfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qstaticnamespacescontainer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qstringvaluefns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsubstringfns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qsystempropertyfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qtimezonefns.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qtracefn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qtypeavailablefn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedentitypublicidfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedentityurifn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedtextavailablefn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qunparsedtextfn.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qxpath10corefunctions.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qxpath20corefunctions.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/functions/qxslt20corefunctions.cpp
)
