list(APPEND GUI_PUBLIC_INCLUDES
   QGraphicsAnchor
   QGraphicsAnchorLayout
   QGraphicsEllipseItem
   QGraphicsGridLayout
   QGraphicsItem
   QGraphicsItemAnimation
   QGraphicsItemGroup
   QGraphicsLayout
   QGraphicsLayoutItem
   QGraphicsLineItem
   QGraphicsLinearLayout
   QGraphicsObject
   QGraphicsPathItem
   QGraphicsPixmapItem
   QGraphicsPolygonItem
   QGraphicsProxyWidget
   QGraphicsRectItem
   QGraphicsRotation
   QGraphicsScale
   QGraphicsScene
   QGraphicsSceneContextMenuEvent
   QGraphicsSceneDragDropEvent
   QGraphicsSceneEvent
   QGraphicsSceneHelpEvent
   QGraphicsSceneHoverEvent
   QGraphicsSceneMouseEvent
   QGraphicsSceneMoveEvent
   QGraphicsSceneResizeEvent
   QGraphicsSceneWheelEvent
   QGraphicsSimpleTextItem
   QGraphicsTextItem
   QGraphicsTransform
   QGraphicsView
   QGraphicsWidget
)

list(APPEND GUI_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qdeclarativelistproperty.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchor.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsellipseitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsgridlayout.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitemanimation.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitemgroup.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslinearlayout.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslineitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsobject.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicspathitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicspixmapitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicspolygonitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsproxywidget.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsrectitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsrotation.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscale.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenecontextmenuevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenedragdropevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenehelpevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenehoverevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenemouseevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenemoveevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneresizeevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenewheelevent.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssimpletextitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstextitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstransform.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsview.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget.h
)

list(APPEND GUI_PRIVATE_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraph_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsgridlayoutengine_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitem_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutitem_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutstyleinfo_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsproxywidget_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene_bsp_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenebsptreeindex_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneindex_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenelinearindex_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstransform_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsview_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgridlayoutengine_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qsimplex_p.h
)

target_sources(CsGui
   PRIVATE
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsanchorlayout_p.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsgridlayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsgridlayoutengine.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitem.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsitemanimation.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayout_p.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutstyleinfo.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslayoutitem.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicslinearlayout.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsproxywidget.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscene_bsp.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsscenebsptreeindex.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneevent.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicssceneindex.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicstransform.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicsview.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgraphicswidget_p.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qgridlayoutengine.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/graphicsview/qsimplex_p.cpp
)
