list(APPEND XMLPATTERNS_PRIVATE_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qabstractnodetest_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanyitemtype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanynodetype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanysimpletype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanytype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccasterlocator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccasterlocators_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccomparatorlocator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccomparatorlocators_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomicmathematicianlocator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomicmathematicianlocators_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomictypedispatch_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomictype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbasictypesfactory_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltinatomictype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltinatomictypes_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltinnodetype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltintypes_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qcardinality_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qcommonsequencetypes_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qebvtype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qemptysequencetype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qgenericsequencetype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qitemtype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qlocalnametest_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qmultiitemtype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnamedschemacomponent_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnamespacenametest_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnonetype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnumerictype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qprimitives_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qqnametest_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qschemacomponent_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qschematypefactory_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qschematype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qsequencetype_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qtypechecker_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/quntyped_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qxsltnodetest_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltintypes.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltinnodetype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccasterlocators.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccomparatorlocators.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomicmathematicianlocators.cpp
)

target_sources(CsXmlPatterns
   PRIVATE
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qabstractnodetest.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanyitemtype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanynodetype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanysimpletype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qanytype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccasterlocator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomiccomparatorlocator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomicmathematicianlocator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qatomictype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbasictypesfactory.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltinatomictype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qbuiltinatomictypes.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qcardinality.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qcommonsequencetypes.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qebvtype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qemptysequencetype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qgenericsequencetype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qitemtype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qlocalnametest.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qmultiitemtype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnamedschemacomponent.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnamespacenametest.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnonetype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qnumerictype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qqnametest.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qschemacomponent.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qschematype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qschematypefactory.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qsequencetype.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qtypechecker.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/quntyped.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/type/qxsltnodetest.cpp
)
