/***********************************************************************
*
* Copyright (c) 2012-2018 Barbara Geller
* Copyright (c) 2012-2018 Ansel Sermersheim
* Copyright (c) 2012-2016 Digia Plc and/or its subsidiary(-ies).
* Copyright (c) 2008-2012 Nokia Corporation and/or its subsidiary(-ies).
* All rights reserved.
*
* This file is part of CopperSpice.
*
* CopperSpice is free software. You can redistribute it and/or
* modify it under the terms of the GNU Lesser General Public License
* version 2.1 as published by the Free Software Foundation.
*
* CopperSpice is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* <http://www.gnu.org/licenses/>.
*
***********************************************************************/

// This file is AUTO GENERATED by qautomaton2cpp.xsl

#ifndef Qxslttokenlookup_P_H
#define Qxslttokenlookup_P_H

#include <QtCore/QString>

QT_BEGIN_NAMESPACE

namespace QPatternist {
class XSLTTokenLookup
{
 public:
   enum NodeName

   {
      NoKeyword,
      AnalyzeString,
      ApplyTemplates,
      As,
      Attribute,
      AttributeSet,
      ByteOrderMark,
      CallTemplate,
      CaseOrder,
      CdataSectionElements,
      Choose,
      Collation,
      Comment,
      Copy,
      CopyNamespaces,
      CopyOf,
      DataType,
      DefaultCollation,
      DefaultValidation,
      DoctypePublic,
      DoctypeSystem,
      Document,
      Element,
      Elements,
      Encoding,
      EscapeUriAttributes,
      ExcludeResultPrefixes,
      ExtensionElementPrefixes,
      Flags,
      ForEach,
      Format,
      Function,
      Href,
      Id,
      If,
      Import,
      ImportSchema,
      Include,
      IncludeContentType,
      Indent,
      InheritNamespaces,
      InputTypeAnnotations,
      Key,
      Lang,
      Match,
      MatchingSubstring,
      MediaType,
      Message,
      Method,
      Mode,
      Name,
      Namespace,
      NonMatchingSubstring,
      NormalizationForm,
      OmitXmlDeclaration,
      Order,
      Otherwise,
      Output,
      OutputVersion,
      Override,
      Param,
      PerformSort,
      PreserveSpace,
      Priority,
      ProcessingInstruction,
      Regex,
      Required,
      ResultDocument,
      SchemaLocation,
      Select,
      Separator,
      Sequence,
      Sort,
      Stable,
      Standalone,
      StripSpace,
      Stylesheet,
      Template,
      Terminate,
      Test,
      Text,
      Transform,
      Tunnel,
      Type,
      UndeclarePrefixes,
      Use,
      UseAttributeSets,
      UseCharacterMaps,
      UseWhen,
      Validation,
      ValueOf,
      Variable,
      Version,
      When,
      WithParam,
      XpathDefaultNamespace
   };

   static inline NodeName toToken(const QString &value);
   static inline NodeName toToken(const QStringRef &value);
   static NodeName toToken(const QChar *data, int length);
   static QString toString(NodeName token);


 private:
   static inline NodeName classifier2(const QChar *data);
   static inline NodeName classifier3(const QChar *data);
   static inline NodeName classifier4(const QChar *data);
   static inline NodeName classifier5(const QChar *data);
   static inline NodeName classifier6(const QChar *data);
   static inline NodeName classifier7(const QChar *data);
   static inline NodeName classifier8(const QChar *data);
   static inline NodeName classifier9(const QChar *data);
   static inline NodeName classifier10(const QChar *data);
   static inline NodeName classifier11(const QChar *data);
   static inline NodeName classifier12(const QChar *data);
   static inline NodeName classifier13(const QChar *data);
   static inline NodeName classifier14(const QChar *data);
   static inline NodeName classifier15(const QChar *data);
   static inline NodeName classifier17(const QChar *data);
   static inline NodeName classifier18(const QChar *data);
   static inline NodeName classifier20(const QChar *data);
   static inline NodeName classifier21(const QChar *data);
   static inline NodeName classifier22(const QChar *data);
   static inline NodeName classifier23(const QChar *data);
   static inline NodeName classifier26(const QChar *data);

};

inline XSLTTokenLookup::NodeName XSLTTokenLookup::toToken(const QString &value)
{
   return toToken(value.constData(), value.length());
}

inline XSLTTokenLookup::NodeName XSLTTokenLookup::toToken(const QStringRef &value)
{
   return toToken(value.constData(), value.length());
}

}

QT_END_NAMESPACE

#endif
