set(MULTIMEDIA_PUBLIC_INCLUDES
    ${MULTIMEDIA_PUBLIC_INCLUDES}
    QAudio
    QAudioFormat
    QAudioInput
    QAudioOutput
    QAudioDeviceInfo
    QAudioEnginePlugin
    QAudioEngineFactoryInterface
    QAbstractAudioDeviceInfo
    QAbstractAudioInput
    QAbstractAudioOutput
)

set(MULTIMEDIA_INCLUDES
    ${MULTIMEDIA_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qabstractaudiodeviceinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qabstractaudioinput.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qabstractaudiooutput.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudio.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioformat.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioinput.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiooutput.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodeviceinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioengineplugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioenginefactoryinterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioengine.h
)

set(MULTIMEDIA_PRIVATE_INCLUDES
    ${MULTIMEDIA_PRIVATE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodevicefactory_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioinput_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiooutput_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodeviceinfo_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudio_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioinput_win32_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiooutput_win32_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodeviceinfo_win32_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiooutput_alsa_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioinput_alsa_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodeviceinfo_alsa_p.h
)

set(MULTIMEDIA_SOURCES
    ${MULTIMEDIA_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudio.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioformat.cpp
)

if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
    set(MULTIMEDIA_SOURCES
        ${MULTIMEDIA_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodeviceinfo_win32_p.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiooutput_win32_p.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioinput_win32_p.cpp
    )
    set(EXTRA_MULTIMEDIA_LIBS
        ${EXTRA_MULTIMEDIA_LIBS}
        winmm
    )
endif()

if(ALSA_FOUND)
    set(MULTIMEDIA_SOURCES
        ${MULTIMEDIA_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiodeviceinfo_alsa_p.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudiooutput_alsa_p.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/audio/qaudioinput_alsa_p.cpp
    )
    set(EXTRA_MULTIMEDIA_LIBS
        ${EXTRA_MULTIMEDIA_LIBS}
        ${ALSA_LIBRARIES}
    )
    include_directories(${ALSA_INCLUDE_DIRS})
endif()