list(APPEND XMLPATTERNS_PUBLIC_INCLUDES
   QAbstractMessageHandler
   QAbstractUriResolver
   QAbstractXmlNodeModel
   QAbstractXmlReceiver
   QSimpleXmlNodeModel
   QSourceLocation
   QXmlFormatter
   QXmlName
   QXmlNamePool
   QXmlQuery
   QXmlResultItems
   QXmlSchema
   QXmlSchemaValidator
   QXmlSerializer
   QXmlItem
   QXmlNodeModelIndex
   QtXmlPatterns
)

list(APPEND XMLPATTERNS_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractmessagehandler.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstracturiresolver.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlitem.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlnodemodelindex.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlnodemodel.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlreceiver.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qsimplexmlnodemodel.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qsourcelocation.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlformatter.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlname.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlnamepool.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlquery.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlresultitems.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschema.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschemavalidator.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlserializer.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qtxmlpatterns.h
)

list(APPEND XMLPATTERNS_PRIVATE_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlforwarditerator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlnodemodel_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlpullprovider_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlreceiver_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qcoloringmessagehandler_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qcoloroutput_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qdeviceresourceloader_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qiodevicedelegate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qnetworkaccessdelegator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qpullbridge_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qresourcedelegator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/quriloader_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qvariableloader_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlpatternistcli_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlquery_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlresultitems_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschema_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschemavalidator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlserializer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qreferencecountedvalue_p.h
)

target_sources(CsXmlPatterns
   PRIVATE
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qvariableloader.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractmessagehandler.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstracturiresolver.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlnodemodel.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlpullprovider.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qabstractxmlreceiver.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qiodevicedelegate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qnetworkaccessdelegator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qpullbridge.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qresourcedelegator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qsimplexmlnodemodel.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qsourcelocation.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/quriloader.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlformatter.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlname.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlnamepool.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlquery.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlresultitems.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschema.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschema_p.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlschemavalidator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qxmlserializer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qcoloringmessagehandler.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/api/qcoloroutput.cpp
)
