set(GUI_PUBLIC_INCLUDES
   ${GUI_PUBLIC_INCLUDES}
	QPlatform_Accessibility
	QPlatform_BackingStore
	QPlatform_Clipboard
	QPlatform_Cursor
	QPlatform_Drag
	QPlatform_FontDatabase
	QPlatform_Integration
	QPlatform_NativeInterface
	QPlatform_OpenGLContext
	QPlatform_Pixmap
	QPlatform_Screen
	QPlatform_Theme
	QPlatform_Window
	QPlatform_WindowFormat
)

set(GUI_INCLUDES
    ${GUI_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_database.h
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_integration.h
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_nativeinterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_pixmap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_screen.h
)

set(GUI_PRIVATE_INCLUDES
    ${GUI_PRIVATE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_screen_p.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_fontdatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_integration.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_nativeinterface.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_pixmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/platform/qplatform_screen.cpp
)
