list(APPEND XMLPATTERNS_PRIVATE_INCLUDES
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qandexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qapplytemplate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qargumentreference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qarithmeticexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qattributeconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qattributenamevalidator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qaxisstep_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcachecells_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcallsite_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcalltargetdescription_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcalltemplate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcastableas_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcastas_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcastingplatform_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcollationchecker_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcombinenodes_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcommentconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcomparisonplatform_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcomputednamespaceconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcontextitem_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcopyof_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcurrentitemstore_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qdocumentconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qdocumentcontentvalidator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qdynamiccontextstore_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qelementconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qemptycontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qemptysequence_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qevaluationcache_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressiondispatch_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressionfactory_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressionsequence_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressionvariablereference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexternalvariableloader_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexternalvariablereference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qfirstitempredicate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qforclause_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qgeneralcomparison_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qgenericpredicate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qifthenclause_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qinstanceof_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qletclause_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qliteral_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qliteralsequence_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qnamespaceconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qncnameconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qnodecomparison_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qnodesort_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoperandsiterator_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoptimizationpasses_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoptimizerblocks_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoptimizerframework_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qorderby_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qorexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qpaircontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qparentnodeaxis_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qpath_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qpositionalvariablereference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qprocessinginstructionconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qqnameconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qquantifiedexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qrangeexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qrangevariablereference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qreturnorderby_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qsimplecontentconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qsinglecontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qsourcelocationreflection_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qstaticbaseuristore_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qstaticcompatibilitystore_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplatemode_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplateparameterreference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplatepattern_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplatepattern_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtextnodeconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtreatas_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtriplecontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtruthpredicate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qunaryexpression_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qunlimitedcontainer_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qunresolvedvariablereference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/quserfunctioncallsite_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/quserfunction_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvalidate_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvaluecomparison_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvariabledeclaration_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvariablereference_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qwithparam_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qxsltsimplecontentconstructor_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcomparisonplatform.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplateinvoker_p.h
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcastingplatform.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qevaluationcache.cpp
)

target_sources(CsXmlPatterns
   PRIVATE
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qandexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qapplytemplate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qargumentreference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qarithmeticexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qattributeconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qattributenamevalidator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qaxisstep.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcallsite.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcalltargetdescription.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcalltemplate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcastableas.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcastas.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcollationchecker.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcombinenodes.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcommentconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcomputednamespaceconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcontextitem.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcopyof.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qcurrentitemstore.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qdocumentconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qdocumentcontentvalidator.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qdynamiccontextstore.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qelementconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qemptycontainer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qemptysequence.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressionfactory.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressionsequence.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexpressionvariablereference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexternalvariableloader.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qexternalvariablereference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qfirstitempredicate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qforclause.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qgeneralcomparison.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qgenericpredicate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qifthenclause.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qinstanceof.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qletclause.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qliteral.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qliteralsequence.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qnamespaceconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qncnameconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qnodecomparison.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qnodesort.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoptimizationpasses.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoptimizerblocks.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qoptimizerframework.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qorderby.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qorexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qpaircontainer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qparentnodeaxis.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qpath.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qpositionalvariablereference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qprocessinginstructionconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qqnameconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qquantifiedexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qrangeexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qrangevariablereference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qreturnorderby.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qsimplecontentconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qsinglecontainer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qsourcelocationreflection.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qstaticbaseuristore.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qstaticcompatibilitystore.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplateinvoker.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplatemode.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtemplateparameterreference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtextnodeconstructor.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtreatas.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtriplecontainer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qtruthpredicate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qunaryexpression.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qunlimitedcontainer.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qunresolvedvariablereference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/quserfunctioncallsite.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/quserfunction.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvalidate.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvaluecomparison.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvariabledeclaration.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qvariablereference.cpp
   ${CMAKE_CURRENT_SOURCE_DIR}/expr/qxsltsimplecontentconstructor.cpp
)
