set(DECLARATIVE_PUBLIC_INCLUDES
    ${DECLARATIVE_PUBLIC_INCLUDES}
    QDeclarativeError
    QDeclarativeEngine
    QDeclarativeContext
    QDeclarativeProperty
    QDeclarativeComponent
    QDeclarativeExpression
    QDeclarativeExtensionInterface
    QDeclarativeExtensionPlugin
    QDeclarativeImageProvider
    QDeclarativeInfo
    QDeclarativeNetworkAccessManagerFactory
    QDeclarativeScriptString
    QDeclarativePropertyValueInterceptor
    QDeclarativePropertyValueSource
    QDeclarativeParserStatus
    QDeclarativeAttachedPropertiesFunc
    QDeclarativeListProperty
    QDeclarativeListReference
    QDeclarativeProperties
    QDeclarativeTypeInfo 
    QtDeclarative
)

set(DECLARATIVE_INCLUDES
    ${DECLARATIVE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarative.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeproperty.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecomponent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativepropertyvaluesource.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativepropertyvalueinterceptor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeparserstatus.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeprivate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeengine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecontext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeexpression.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeerror.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeimageprovider.h 
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativenetworkaccessmanagerfactory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeextensioninterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeextensionplugin.h  
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativescriptstring.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeattachedpropertiesfunc.h 
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelistproperty.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelistreference.h  
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeproperties.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypeinfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qtdeclarative.h
)

set(DECLARATIVE_PRIVATE_INCLUDES
    ${DECLARATIVE_PRIVATE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeparser_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeglobal_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeinstruction_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevmemetaobject_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativebinding_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativebinding_p_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecomponent_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecustomparser_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecustomparser_p_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeboundsignal_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeproxymetaobject_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevme_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecompiler_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeengine_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeexpression_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativedom_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativedom_p_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativerefcount_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativemetatype_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativestringconverters_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeproperty_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecontext_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeinclude_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypeloader_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelist_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativedata_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativescriptparser_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativerewrite_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qpodvector_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qbitfield_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevaluetype_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecompiledbindings_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativefastproperties_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativexmlhttprequest_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativesqldatabase_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qmetaobjectbuilder_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativewatcher_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecleanup_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativepropertycache_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativenotifier_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeintegercache_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypenotavailable_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypenamecache_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeobjectscriptclass_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecontextscriptclass_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeglobalscriptclass_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevaluetypescriptclass_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypenamescriptclass_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelistscriptclass_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeworkerscript_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeguard_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativedirparser_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeimport_p.h
)

set(DECLARATIVE_SOURCES
    ${DECLARATIVE_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeparser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeinstruction.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevmemetaobject.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeengine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeexpression.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativebinding.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeproperty.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecomponent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecontext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeinclude.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecustomparser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativepropertyvaluesource.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativepropertyvalueinterceptor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeproxymetaobject.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevme.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecompiler.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecompileddata.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeboundsignal.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativedom.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativerefcount.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativemetatype.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativestringconverters.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeparserstatus.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypeloader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeinfo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeerror.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativescriptparser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativerewrite.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevaluetype.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecompiledbindings.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativefastproperties.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativexmlhttprequest.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativesqldatabase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qmetaobjectbuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativewatcher.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecleanup.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativepropertycache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativenotifier.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeintegercache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypenotavailable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypenamecache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativescriptstring.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeobjectscriptclass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativecontextscriptclass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeglobalscriptclass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativevaluetypescriptclass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativetypenamescriptclass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelistscriptclass.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeworkerscript.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeimageprovider.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativenetworkaccessmanagerfactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativedirparser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeextensionplugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativeimport.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/qml/qdeclarativelist.cpp
)
