set(GUI_PUBLIC_INCLUDES
    ${GUI_PUBLIC_INCLUDES}
    QCDEStyle
    QCleanlooksStyle
    QCommonStyle
    QGtkStyle
    QMacStyle
    QMotifStyle
    QPlastiqueStyle
    QProxyStyle
    QStyle
    QStyleFactory
    QStyleFactoryInterface
    QStyleHintReturn
    QStyleHintReturnMask
    QStyleHintReturnVariant
    QStyleOption
    QStyleOptionButton
    QStyleOptionComboBox
    QStyleOptionComplex
    QStyleOptionDockWidget
    QStyleOptionDockWidgetV2
    QStyleOptionFocusRect
    QStyleOptionFrame
    QStyleOptionFrameV2
    QStyleOptionFrameV3
    QStyleOptionGraphicsItem
    QStyleOptionGroupBox
    QStyleOptionHeader
    QStyleOptionMenuItem
    QStyleOptionProgressBar
    QStyleOptionProgressBarV2
    QStyleOptionRubberBand
    QStyleOptionSizeGrip
    QStyleOptionSlider
    QStyleOptionSpinBox
    QStyleOptionTab
    QStyleOptionTabBarBase
    QStyleOptionTabBarBaseV2
    QStyleOptionTabV2
    QStyleOptionTabV3
    QStyleOptionTabWidgetFrame
    QStyleOptionTabWidgetFrameV2
    QStyleOptionTitleBar
    QStyleOptionToolBar
    QStyleOptionToolBoxV2
    QStyleOptionToolBox
    QStyleOptionToolBarV2
    QStyleOptionToolButton
    QStyleOptionViewItem
    QStyleOptionViewItemV2
    QStyleOptionViewItemV3
    QStyleOptionViewItemV4
    QStylePlugin
    QWindowsStyle
    QWindowsVistaStyle
    QWindowsXPStyle
)

set(GUI_INCLUDES
    ${GUI_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcdestyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcleanlooksstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcommonstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qgtkstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmacstyle_mac.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmacstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmotifstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qplastiquestyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qproxystyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylefactory.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylefactoryinterface.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylehintreturn.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylehintreturnmask.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylehintreturnvariant.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoption.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionbutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptioncombobox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptioncomplex.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiondockwidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiondockwidgetv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionfocusrect.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionframe.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionframev2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionframev3.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiongraphicsitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiongroupbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionheader.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionmenuitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionprogressbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionprogressbarv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionrubberband.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionsizegrip.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionslider.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionspinbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontab.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontabbarbase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontabbarbasev2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontabv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontabv3.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontabwidgetframe.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontabwidgetframev2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontitlebar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontoolbar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontoolbox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontoolboxv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontoolbarv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptiontoolbutton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionviewitem.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionviewitemv2.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionviewitemv3.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoptionviewitemv4.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleplugin.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsstyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsvistastyle.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsxpstyle.h
)

set(GUI_PRIVATE_INCLUDES
    ${GUI_PRIVATE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcommonstylepixmaps_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcleanlooksstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcommonstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmotifstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qgtkstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qgtkpainter_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmacstyle_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmacstylepixmaps_mac_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylehelper_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qproxystyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylesheetstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsxpstyle_p.h
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsvistastyle_p.h
)

set(GUI_SOURCES
    ${GUI_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmotifstyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylefactory.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleoption.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyleplugin.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylehelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcommonstyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qproxystyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylesheetstyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstylesheetstyle_default.cpp
    # ${CMAKE_CURRENT_SOURCE_DIR}/styles/qrc_qstyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qplastiquestyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcleanlooksstyle.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qcdestyle.cpp
)

set(EXTRA_DIST
    ${EXTRA_DIST}
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/qstyle.qrc
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/filelink-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/filelink-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/filelink-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/file-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/file-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/file-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/newdirectory-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/newdirectory-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/newdirectory-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/parentdir-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/parentdir-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/parentdir-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dvd-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dvd-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dvd-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/cdr-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/cdr-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/cdr-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/floppy-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/floppy-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/floppy-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/harddrive-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/harddrive-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/harddrive-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/trash-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/trash-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/trash-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/networkdrive-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/networkdrive-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/networkdrive-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/computer-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/computer-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/desktop-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/desktop-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dirclosed-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dirclosed-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dirclosed-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dirlink-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dirlink-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dirlink-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/diropen-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/diropen-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/diropen-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/left-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/left-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/left-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/right-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/right-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/right-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/up-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/up-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/up-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/down-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/down-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/down-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/filecontents-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/filecontents-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/filecontents-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/fileinfo-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/fileinfo-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/fileinfo-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/viewdetailed-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/viewdetailed-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/viewdetailed-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/viewlist-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/viewlist-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/viewlist-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/fontbitmap-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/fonttruetype-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-apply-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-apply-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-apply-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-cancel-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-cancel-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-cancel-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-clear-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-clear-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-clear-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-close-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-close-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-close-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-delete-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-delete-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-delete-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-help-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-help-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-help-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-no-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-no-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-no-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-ok-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-ok-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-ok-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-open-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-open-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-open-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-save-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-save-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-save-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-yes-128.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-yes-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-yes-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-closetab-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-closetab-down-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/standardbutton-closetab-hover-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/refresh-24.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/refresh-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/stop-24.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/stop-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-stop-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-stop-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-play-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-play-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-pause-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-pause-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-seek-forward-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-seek-forward-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-seek-backward-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-seek-backward-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-skip-forward-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-skip-forward-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-skip-backward-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-skip-backward-32.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-volume-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/media-volume-muted-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/closedock-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/closedock-down-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dockdock-16.png
    ${CMAKE_CURRENT_SOURCE_DIR}/styles/images/dockdock-down-16.png
)

if(X11_FOUND)
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsstyle.cpp
    )
endif()

if(GTK2_FOUND)
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qgtkstyle.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qgtkpainter.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qgtkstyle_p.cpp
    )
    set(EXTRA_GUI_LIBS
        ${EXTRA_GUI_LIBS}
        ${GTK2_LIBRARIES}
    )
    include_directories(${GTK2_INCLUDE_DIRS})
    add_definitions(${GTK2_DEFINITIONS})
else()
    add_definitions(-DQT_NO_STYLE_GTK)
endif()


if(${CMAKE_SYSTEM_NAME} MATCHES "Win32")
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsstyle.cpp
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsxpstyle.cpp 
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsvistastyle.cpp
    )
endif()


if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(GUI_SOURCES
        ${GUI_SOURCES}
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qwindowsstyle.cpp 
        ${CMAKE_CURRENT_SOURCE_DIR}/styles/qmacstyle_mac.mm
    )
    add_definitions(-DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK)
endif()
