set(CORE_PUBLIC_INCLUDES
    ${CORE_PUBLIC_INCLUDES}
    QCache
    QContiguousCache
    QFlatMap
    QHash
    QHashIterator
    QLinkedList
    QLinkedListIterator
    QList
    QListIterator
    QMap
    QMapIterator
    QMultiHash
    QMultiMap
    QMutableHashIterator
    QMutableLinkedListIterator
    QMutableListIterator
    QMutableMapIterator
    QMutableSetIterator
    QMutableStringListIterator
    QMutableVectorIterator
    QQueue
    QSet
    QSetIterator
    QStack
    QStringList
    QStringListIterator
    QVector
    QVectorIterator
)

set(CORE_INCLUDES
    ${CORE_INCLUDES}
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qcache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qcontainerfwd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qcontiguouscache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qflatmap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qhash.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qhashfunc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qhashfwd.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qhashiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qlinkedlist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qlinkedlistiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qlist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qlistiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmapfunc.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmapiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmultihash.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmultimap.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablehashiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablelinkedlistiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablelistiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablemapiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablesetiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablestringlistiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmutablevectoriterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qqueue.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qset.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qsetiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qstack.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qstringlist.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qstringlistiterator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qvector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qvectoriterator.h
)

set(CORE_SOURCES
    ${CORE_SOURCES}
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qcontiguouscache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qflatmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qhash.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qlinkedlist.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qlist.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qmap.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qqueue.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qstringlist.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/containers/qvector.cpp


