set(COPPERSPICE_VERSION_MAJOR "@BUILD_MAJOR@")
set(COPPERSPICE_VERSION_MINOR "@BUILD_MINOR@")
set(COPPERSPICE_VERSION_PATCH "@BUILD_MICRO@")
set(COPPERSPICE_VERSION "@BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_MICRO@")
