#
# Copyright (C) 2012-2018 Barbara Geller
# Copyright (C) 2012-2018 Ansel Sermersheim
# All rights reserved.
#

set(COPPERSPICE_VERSION_MAJOR "@BUILD_MAJOR@")
set(COPPERSPICE_VERSION_MINOR "@BUILD_MINOR@")
set(COPPERSPICE_VERSION_PATCH "@BUILD_MICRO@")
set(COPPERSPICE_VERSION "@BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_MICRO@")
